#! perl
# Based on https://superuser.com/questions/1005447/how-can-i-enable-cursor-scrolling-via-mousewheel-in-emacs-with-urxvt

sub simulate_keypress {
    my ($self, $type) = @_; # type: 0:up, 1:down
    my $keycode_up = 111;
    my $keycode_down = 116;
    my $numlines = 3;
    my $keycode = 0;

    if ($type eq 0) {
	$keycode = $keycode_up;
    } elsif ($type eq 1) {
	$keycode = $keycode_down;
    } else {
	return;
    }

    for (my $i = 0; $i ne $numlines; $i++) {
	$self->key_press(0, $keycode);
	$self->key_release(0, $keycode);
    }
}

sub on_button_release {
    my ($self, $event) = @_;

    return if !$self->current_screen;

    if ($event->{button} eq "4") {
	# Scroll up
	$self->simulate_keypress(0);
	return 1;
    } elsif ($event->{button} eq "5") {
	# Scroll down
	$self->simulate_keypress(1);
	return 1;
    }
    return;
}
