#!/bin/sh
#SS="$HOME/.i3lock-blur.png"
#scrot "$SS"
#convert "$SS" -blur 0x5 "$SS"
#i3lock -i "$SS" "$@"
#rm "$SS"
i3lock "$@"
todo=~/Dropbox/org/todos.org
if [ -f "$todo" ]; then
	notify-send -a "To Dos" -t 30000 "$(echo "$todo\n==="; grep '^\*' "$todo" | tac)"
fi
