#
# node/npm
#

# Local package directory
npm_dirname=".npm_prefix"
if [[ ! -e "$HOME/$npm_dirname" ]]; then
	mkdir "$HOME/$npm_dirname"
fi

# Base configuration
npm_config="$HOME/.npmrc"
if [[ ! -e $npm_config ]]; then
cat > "$npm_config" << END
# Auto generated by ~/.bashrc
prefix="\${HOME}/$npm_dirname"
END
fi

# Set path (mainly for local usage, so there's not need to include that in
# ~/.profile).
export PATH="$HOME/$npm_dirname/bin:$PATH"

unset npm_dirname
unset npm_config
